#ifndef RECEPTORUTILS_H
#define RECEPTORUTILS_H

class Receptor;
class QByteArray;

enum class ReceptorType : int {
    UNKNOWN_RECEPTOR = 0,
    TILT_RECEPTOR,
    LIGHT_RECEPTOR,
    COMPASS_RECEPTOR,
    PROXIMITY_RECEPTOR,
    ORIENTATION_RECEPTOR,
    ACCELEROMETER_RECEPTOR,
    AMBIENT_LIGHT_RECEPTOR,
    MAGNETOMETER_RECEPTOR,
};

#endif // RECEPTORUTILS_H
